#ifndef ERROR_H
#define ERROR_H
enum errorname
{
	NO_ERROR=0,
	UNKNOWN_SYMBOL=1,//unknown symbol in line
	STRING_TOO_LONG,//string is too long
	WRONG_FORMAT_INTEGER,//wrong format integer
	WRONG_FORMAT_IDEN,//wrong format IDEN
	WRONG_FORMAT_CHAR,
	WRONG_PARA_KIND,
	WRONG_PARA_NUM,
	WRONG_CONST_MISSING_TK,
	WRONG_EXPRESSION,
	UNFINISHED_STRING,//\'\"\'dismatch
	MISSING_SEMICN,//sentence misses semicn
	PARENT_DISMATCH,//parent dismatch
	BRACK_DISMATCH,
	WITHOUT_DECLARATION,
	RE_DECLARATION,
	CODE_AFTER_MAIN,
	SCANF_NOINTONCHAR,
	EMPTY_CONDITION,
	ARRAY_INFO_LSS0,
	ARRAY_OVERFLOW,
	ASSIGN_WRONG_LEFT,
	FULL_TABLE,
	DEF_FUNC_MISS_PARENT,
	DEF_FUNC_MISS_NAME,
	WRONG_DEFINITION,
	CONST_DEF_MISS_IDEN,
	CONST_DEF_ERROR,
	INT_WRONG,
	VAR_KIND_ERROR,
	PARA_TABLE_MISS_RPARENT,
	FUNC_MISS_LBRACE,
	FUNC_MISS_RBRACE,
	PARA_KIND_ERROR,
	PARA_MISS_IDEN,
	WRONG_STATEMENT,
	ASSIGN_ERROR,
	CONDITION_ERROR,
	DO_WHILE_ERROR,
	CONSTANT_ERROR,
	MISS_CASE,
	SCANF_MISS_IDEN,
	PRINTF_ERROR,
	RETURN_WRONG_TYPE
};
int error (int errortype);
#endif
